alias app.cat="cat alias.sh"
alias app.info="docker container ls -a"
alias app.ls="docker compose ls"
alias app.lg="docker compose logs"
alias app.rest="docker compose restart"
alias app.ref="docker compose down && docker compose up -d"
alias app.wat="docker compose up"
alias app.up="docker compose up -d"
alias app.dw="docker compose down"
alias app.ip='docker inspect app_http | grep "IPAddress"'
alias app.prune="docker container prune && docker volume prune && docker network prune"
alias app.bash="docker exec -it app bash"
alias app.exec="docker exec -it app"
alias app.php="app.exec php"
alias app.composer="app.exec composer"
alias app.art="app.php artisan"
alias app.init="cp docker/.env.example .env && app.composer install && app.art key:generate"
alias app.cache-clear="app.art view:clear && app.art route:clear && app.art config:clear"
alias app.cache="app.art view:cache && app.art config:cache && app.art route:cache"
alias app.cache-refresh="app.cache-clear && app.cache"
alias app.redis-clear="docker exec -it app_cache_db redis-cli FLUSHALL"
alias app.migrate="app.art migrate"
alias app.seed="app.art db:seed"
alias app.test="app.art test --env=testing"
alias app.coverage="app.php vendor/bin/pest --coverage --coverage-html=public/tests/coverage"
alias app.lint="app.php ./vendor/bin/pint"
alias app.captainhook="app.php ./vendor/bin/captainhook"
alias app.psalm="app.php ./vendor/bin/psalm --no-cache"
alias app.psalm-show="app.php ./vendor/bin/psalm --show-info=true --no-cache"
alias app.tinker="app.art tinker"
alias app.fake="app.art appurno:fake"
alias app.route="app.art route:list"
